[project]
name = "asteroid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.10",
    "numpy>=2.3.3",
    "pyqt6>=6.9.1",
    "reportlab>=4.4.10",
    "ruff>=0.15.12",
]

[project.optional-dependencies]
dev = ["ruff>=0.9", "mypy>=1.8"]

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP", "C90"]
ignore = ["D203", "D213", "C901"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
force-sort-within-sections = true
force-single-line = true
combine-as-imports = true
order-by-type = true
lines-after-imports = -1
known-first-party = ["sqlvc"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true
no_implicit_optional = true
disable_error_code = "no-untyped-def"