const translations = <String, Map<String, String>>{
  'en': {
    'elements': 'Elements',
    'relationships': 'Relationships',
    'properties': 'Properties',
    'options': 'Options',
    'addElement': 'Add element',
    'connect': 'Connect',
    'delete': 'Delete',
    'name': 'Name',
    'type': 'Type',
    'position': 'Position',
    'size': 'Size',
    'textSize': 'Text size',
    'colors': 'Colors',
    'fillColor': 'Fill',
    'borderColor': 'Border',
    'textColor': 'Text',
    'subcanvas': 'Behavior canvas',
    'subcanvasHint': 'Shows the internal intentional elements of this actor or agent.',
    'enterCanvas': 'Open behavior canvas',
    'exitCanvas': 'Return to main canvas',
    'activeCanvas': 'Editing inside {name}',
    'moveCanvas': 'Move canvas',
    'resizeCanvas': 'Resize canvas',
    'canvasRadius': 'Canvas radius',
    'canvasHorizontal': 'Canvas horizontal position',
    'canvasVertical': 'Canvas vertical position',
    'apply': 'Apply',
    'cancel': 'Cancel',
    'newProject': 'New project',
    'openProject': 'Open project',
    'exportProject': 'Export project',
    'exportDiagram': 'Export diagram image',
    'exportDiagramTitle': 'Export diagram as PNG',
    'diagramExported': 'Diagram exported.',
    'error.diagramExport': 'Could not export the diagram: {details}',
    'exportTitle': 'Export Asteroid project',
    'darkMode': 'Dark mode',
    'lightMode': 'Light mode',
    'validatorOn': 'Validator on',
    'validatorOff': 'Validator off',
    'help': 'Documentation',
    'about': 'About Asteroid',
    'undo': 'Undo',
    'redo': 'Redo',
    'resetView': 'Reset view',
    'projectMenu': 'Project menu',
    'selectFirst': 'Select the first element',
    'selectDestination': 'Select the destination',
    'projectCleared': 'Project cleared',
    'projectImported': 'Project imported.',
    'projectExported': 'Project exported.',
    'newProjectWarning': 'This clears the current diagram. Export it first if you want to keep a separate copy.',
    'languageSpanish': 'Español',
    'languageEnglish': 'English',
    'reverseDirection': 'Reverse direction',
    'source': 'Source',
    'destination': 'Destination',
    'noSelection': 'Select an element or relationship first.',
    'defaultProject': 'Untitled model',
    'node.actor': 'Actor',
    'node.agent': 'Agent',
    'node.hardGoal': 'Hard goal',
    'node.softGoal': 'Soft goal',
    'node.plan': 'Plan',
    'node.resource': 'Resource',
    'edge.dependency': 'Dependency',
    'edge.why': 'Why',
    'edge.meansEnd': 'Means-End',
    'edge.or': 'OR decomposition',
    'edge.and': 'AND decomposition',
    'edge.contribution': 'Contribution',
    'validation.entityLink': 'A {relationship} relationship cannot connect two actors or agents. Use intentional elements inside their behavior canvases.',
    'validation.entityInsideEntity': 'Actors and agents cannot be added inside another actor or agent. Add goals, soft goals, plans, or resources instead.',
    'validation.canvasScope': 'While editing a behavior canvas, relationships can only connect elements inside that same canvas.',
    'error.fileUnreadable': 'The selected file could not be read.',
    'error.invalidFile': 'Invalid Asteroid file: {details}',
    'error.importFailed': 'Could not open the project: {details}',
    'error.exportFailed': 'Export failed: {details}',
    'exportCancelled': 'Export cancelled.',
    'docs.title': 'Asteroid Mobile Guide',
    'docs.startTitle': 'Create and navigate',
    'docs.startBody': 'Use Add element to place actors, agents, goals, soft goals, plans, and resources. Drag a node to move it. Drag empty canvas space to pan and pinch to zoom. The page grows in 900 px sections near any edge and automatically removes unused sections after content moves back or is deleted. Reset view fits the complete diagram to the screen.',
    'docs.linksTitle': 'Create relationships',
    'docs.linksBody': 'Choose Connect, select a relationship type, tap the source element, and then tap the destination. Tap near a relationship line to select it. Its properties let you change the type or reverse its direction.',
    'docs.propertiesTitle': 'Edit properties and colors',
    'docs.propertiesBody': 'Select a node and open Properties. You can edit its name, size, text size, fill, border, and text colors. Actors and agents can expose a behavior canvas for their internal intentional elements.',
    'docs.subcanvasTitle': 'Behavior canvases',
    'docs.subcanvasBody': 'Tap an actor or agent to enter its behavior canvas. New goals, soft goals, plans, and resources are then created inside it. Drag the green center handle to move the circle and its contents; drag the amber edge handle to resize it. Use Return to main canvas when finished.',
    'docs.validationTitle': 'Tropos validation',
    'docs.validationBody': 'Validator mode blocks relationships directly between two actors or agents. Model dependencies through intentional elements inside behavior canvases. Disable validation only when intentionally drafting an incomplete model.',
    'docs.filesTitle': 'Projects and compatibility',
    'docs.filesBody': 'Work is autosaved locally. Export project creates an .astr JSON file that can be reopened on supported mobile devices. Open project accepts exported .astr and JSON files from Android and iOS document providers. Export diagram image creates a cropped PNG of the visible model.',
    'about.title': 'Asteroid Mobile',
    'about.version': 'Version 1.0.0',
    'about.body': 'Asteroid Mobile is a touch-first companion for creating Tropos and i* diagrams on the go. Model actors, agents, goals, resources, softgoals, plans, and their relationships with a focused mobile editing experience.',
    'about.credits': 'Credits',
    'about.createdBy': 'Created by: Ing. Andy Clemente',
    'about.originalIdea': 'Original idea by: Ing. Daryll Lorenzo',
    'docs.historyTitle': 'Undo and redo',
    'docs.historyBody': 'Node creation, movement, property changes, relationships, and deletions are kept in the local history. Use the app bar arrows to undo or redo up to 60 recent document states.',
  },
  'es': {
    'elements': 'Elementos',
    'relationships': 'Relaciones',
    'properties': 'Propiedades',
    'options': 'Opciones',
    'addElement': 'Agregar elemento',
    'connect': 'Conectar',
    'delete': 'Eliminar',
    'name': 'Nombre',
    'type': 'Tipo',
    'position': 'Posición',
    'size': 'Tamaño',
    'textSize': 'Tamaño del texto',
    'colors': 'Colores',
    'fillColor': 'Relleno',
    'borderColor': 'Borde',
    'textColor': 'Texto',
    'subcanvas': 'Lienzo de comportamiento',
    'subcanvasHint': 'Muestra los elementos intencionales internos de este actor o agente.',
    'enterCanvas': 'Abrir lienzo de comportamiento',
    'exitCanvas': 'Volver al lienzo principal',
    'activeCanvas': 'Editando dentro de {name}',
    'moveCanvas': 'Mover lienzo',
    'resizeCanvas': 'Cambiar tamaño del lienzo',
    'canvasRadius': 'Radio del lienzo',
    'canvasHorizontal': 'Posición horizontal del lienzo',
    'canvasVertical': 'Posición vertical del lienzo',
    'apply': 'Aplicar',
    'cancel': 'Cancelar',
    'newProject': 'Nuevo proyecto',
    'openProject': 'Abrir proyecto',
    'exportProject': 'Exportar proyecto',
    'exportDiagram': 'Exportar imagen del diagrama',
    'exportDiagramTitle': 'Exportar diagrama como PNG',
    'diagramExported': 'Diagrama exportado.',
    'error.diagramExport': 'No se pudo exportar el diagrama: {details}',
    'exportTitle': 'Exportar proyecto de Asteroid',
    'darkMode': 'Modo oscuro',
    'lightMode': 'Modo claro',
    'validatorOn': 'Validador activo',
    'validatorOff': 'Validador inactivo',
    'help': 'Documentación',
    'about': 'Acerca de Asteroid',
    'undo': 'Deshacer',
    'redo': 'Rehacer',
    'resetView': 'Restablecer vista',
    'projectMenu': 'Menú del proyecto',
    'selectFirst': 'Selecciona el primer elemento',
    'selectDestination': 'Selecciona el destino',
    'projectCleared': 'Proyecto limpiado',
    'projectImported': 'Proyecto importado.',
    'projectExported': 'Proyecto exportado.',
    'newProjectWarning': 'Esto elimina el diagrama actual. Expórtalo primero si deseas conservar una copia separada.',
    'languageSpanish': 'Español',
    'languageEnglish': 'English',
    'reverseDirection': 'Invertir dirección',
    'source': 'Origen',
    'destination': 'Destino',
    'noSelection': 'Selecciona primero un elemento o una relación.',
    'defaultProject': 'Modelo sin título',
    'node.actor': 'Actor',
    'node.agent': 'Agente',
    'node.hardGoal': 'Meta',
    'node.softGoal': 'Meta flexible',
    'node.plan': 'Plan',
    'node.resource': 'Recurso',
    'edge.dependency': 'Dependencia',
    'edge.why': 'Por qué',
    'edge.meansEnd': 'Medio-Fin',
    'edge.or': 'Descomposición OR',
    'edge.and': 'Descomposición AND',
    'edge.contribution': 'Contribución',
    'validation.entityLink': 'Una relación {relationship} no puede conectar directamente dos actores o agentes. Usa elementos intencionales dentro de sus lienzos de comportamiento.',
    'validation.entityInsideEntity': 'No se pueden agregar actores o agentes dentro de otro actor o agente. Agrega metas, metas flexibles, planes o recursos.',
    'validation.canvasScope': 'Mientras editas un lienzo de comportamiento, las relaciones solo pueden conectar elementos dentro de ese mismo lienzo.',
    'error.fileUnreadable': 'No se pudo leer el archivo seleccionado.',
    'error.invalidFile': 'Archivo de Asteroid no válido: {details}',
    'error.importFailed': 'No se pudo abrir el proyecto: {details}',
    'error.exportFailed': 'No se pudo exportar: {details}',
    'exportCancelled': 'Exportación cancelada.',
    'docs.title': 'Guía de Asteroid Mobile',
    'docs.startTitle': 'Crear y navegar',
    'docs.startBody': 'Usa Agregar elemento para colocar actores, agentes, metas, metas flexibles, planes y recursos. Arrastra un nodo para moverlo, desplázate por el espacio vacío y pellizca para ampliar. La página crece en secciones de 900 px cerca de cualquier borde y elimina automáticamente las secciones sin uso cuando el contenido regresa o se elimina. Restablecer vista ajusta el diagrama completo a la pantalla.',
    'docs.linksTitle': 'Crear relaciones',
    'docs.linksBody': 'Elige Conectar, selecciona el tipo de relación, toca el elemento de origen y después el destino. Toca cerca de una línea para seleccionarla. Sus propiedades permiten cambiar el tipo o invertir su dirección.',
    'docs.propertiesTitle': 'Editar propiedades y colores',
    'docs.propertiesBody': 'Selecciona un nodo y abre Propiedades. Puedes editar su nombre, tamaño, tamaño del texto y los colores de relleno, borde y texto. Los actores y agentes pueden mostrar un lienzo de comportamiento para sus elementos intencionales internos.',
    'docs.subcanvasTitle': 'Lienzos de comportamiento',
    'docs.subcanvasBody': 'Toca un actor o agente para entrar en su lienzo de comportamiento. Las nuevas metas, metas flexibles, planes y recursos se crean dentro de él. Arrastra el control verde central para mover el círculo con su contenido y el control ámbar del borde para cambiar su tamaño. Usa Volver al lienzo principal al terminar.',
    'docs.validationTitle': 'Validación de Tropos',
    'docs.validationBody': 'El modo validador bloquea relaciones directas entre dos actores o agentes. Modela las dependencias mediante elementos intencionales dentro de los lienzos de comportamiento. Desactiva la validación solo cuando necesites crear un borrador incompleto.',
    'docs.filesTitle': 'Proyectos y compatibilidad',
    'docs.filesBody': 'El trabajo se guarda automáticamente en el dispositivo. Exportar proyecto crea un archivo JSON .astr que puede abrirse de nuevo en dispositivos móviles compatibles. Abrir proyecto acepta archivos .astr y JSON exportados desde los proveedores de documentos de Android e iOS. Exportar imagen del diagrama crea un PNG recortado del modelo visible.',
    'about.title': 'Asteroid Mobile',
    'about.version': 'Versión 1.0.0',
    'about.body': 'Asteroid Mobile es un compañero táctil para crear diagramas Tropos e i* en cualquier lugar. Permite modelar actores, agentes, metas, recursos, metas flexibles, planes y sus relaciones desde una experiencia móvil enfocada.',
    'about.credits': 'Créditos',
    'about.createdBy': 'Creado por: Ing. Andy Clemente',
    'about.originalIdea': 'Idea original de: Ing. Daryll Lorenzo',
    'docs.historyTitle': 'Deshacer y rehacer',
    'docs.historyBody': 'La creación, el movimiento, los cambios de propiedades, las relaciones y las eliminaciones se guardan en el historial local. Usa las flechas de la barra superior para deshacer o rehacer hasta 60 estados recientes.',
  },
};

String tr(String language, String key, [Map<String, Object?> values = const {}]) {
  var result = translations[language]?[key] ?? translations['en']?[key] ?? key;
  for (final entry in values.entries) {
    result = result.replaceAll('{${entry.key}}', '${entry.value}');
  }
  return result;
}

String nodeKindLabel(String language, String key) => tr(language, 'node.$key');

String edgeKindLabel(String language, String key) => tr(language, 'edge.$key');
